### ISSUE TITLE
PHP Fatal error: Uncaught RuntimeException: Unable to claim actions.

### ISSUE THREAD

**Issue by csalzano** [hCaptcha/hcaptcha-wordpress-plugin#396]
Seems like hCaptcha for WordPress is running Action Scheduler without installing Action Scheduler. Here is debug.log snippet. These are mostly caught errors until the fatal error at the bottom.

```
[24-Mar-2025 13:08:14 UTC] WordPress database error Table 'uaosufhuas.wp_actionscheduler_actions' doesn't exist for query SELECT a.action_id FROM wp_actionscheduler_actions a LEFT JOIN wp_actionscheduler_groups g ON g.group_id=a.group_id WHERE 1=1 AND g.slug='hcaptcha' AND a.hook='async_migrate_4_11_0' AND a.args='[]' AND a.status IN ('pending', 'in-progress', 'failed', 'canceled') ORDER BY a.scheduled_date_gmt ASC LIMIT 0, 5 made by require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('init'), WP_Hook->do_action, WP_Hook->apply_filters, ActionScheduler::{closure}, do_action('action_scheduler_init'), WP_Hook->do_action, WP_Hook->apply_filters, HCaptcha\Migrations\Migrations->HCaptcha\Migrations\{closure}, HCaptcha\Migrations\Migrations->create_as_action, as_get_scheduled_actions, ActionScheduler_HybridStore->query_actions, ActionScheduler_DBStore->query_actions
[24-Mar-2025 13:08:14 UTC] WordPress database error Table 'uaosufhuas.wp_actionscheduler_actions' doesn't exist for query SELECT a.action_id FROM wp_actionscheduler_actions a LEFT JOIN wp_actionscheduler_groups g ON g.group_id=a.group_id WHERE 1=1 AND g.slug='hcaptcha' AND a.hook='async_migrate_4_11_0' AND a.args='[]' AND a.status IN ('pending') ORDER BY a.scheduled_date_gmt ASC LIMIT 0, 1 made by require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('init'), WP_Hook->do_action, WP_Hook->apply_filters, ActionScheduler::{closure}, do_action('action_scheduler_init'), WP_Hook->do_action, WP_Hook->apply_filters, HCaptcha\Migrations\Migrations->HCaptcha\Migrations\{closure}, HCaptcha\Migrations\Migrations->create_as_action, as_enqueue_async_action, ActionScheduler_ActionFactory->create, ActionScheduler_ActionFactory->store_unique_action, ActionScheduler_HybridStore->find_action, ActionScheduler_Store->find_action, ActionScheduler_DBStore->query_actions
[24-Mar-2025 13:08:14 UTC] WordPress database error Table 'uaosufhuas.wp_actionscheduler_groups' doesn't exist for query SELECT group_id FROM wp_actionscheduler_groups WHERE slug='hcaptcha' made by require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('init'), WP_Hook->do_action, WP_Hook->apply_filters, ActionScheduler::{closure}, do_action('action_scheduler_init'), WP_Hook->do_action, WP_Hook->apply_filters, HCaptcha\Migrations\Migrations->HCaptcha\Migrations\{closure}, HCaptcha\Migrations\Migrations->create_as_action, as_enqueue_async_action, ActionScheduler_ActionFactory->create, ActionScheduler_ActionFactory->store_unique_action, ActionScheduler_HybridStore->save_action, ActionScheduler_DBStoreMigrator->save_action, ActionScheduler_DBStore->save_action, ActionScheduler_DBStore->save_action_to_db, ActionScheduler_DBStore->get_group_ids
[24-Mar-2025 13:08:14 UTC] WordPress database error Table 'uaosufhuas.wp_actionscheduler_groups' doesn't exist for query SHOW FULL COLUMNS FROM `wp_actionscheduler_groups` made by require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('init'), WP_Hook->do_action, WP_Hook->apply_filters, ActionScheduler::{closure}, do_action('action_scheduler_init'), WP_Hook->do_action, WP_Hook->apply_filters, HCaptcha\Migrations\Migrations->HCaptcha\Migrations\{closure}, HCaptcha\Migrations\Migrations->create_as_action, as_enqueue_async_action, ActionScheduler_ActionFactory->create, ActionScheduler_ActionFactory->store_unique_action, ActionScheduler_HybridStore->save_action, ActionScheduler_DBStoreMigrator->save_action, ActionScheduler_DBStore->save_action, ActionScheduler_DBStore->save_action_to_db, ActionScheduler_DBStore->get_group_ids, ActionScheduler_DBStore->create_group
[24-Mar-2025 13:08:14 UTC] WordPress database error Table 'uaosufhuas.wp_actionscheduler_actions' doesn't exist for query 
INSERT INTO wp_actionscheduler_actions ( `hook`, `status`, `scheduled_date_gmt`, `scheduled_date_local`, `schedule`, `group_id`, `priority`, `args` )
SELECT 'async_migrate_4_11_0', 'pending', '2025-03-24 13:08:14', '2025-03-24 13:08:14', 'O:28:\"ActionScheduler_NullSchedule\":0:{}', 0, 10, '[]' FROM DUAL
WHERE ( SELECT NULL FROM DUAL ) IS NULL made by require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('init'), WP_Hook->do_action, WP_Hook->apply_filters, ActionScheduler::{closure}, do_action('action_scheduler_init'), WP_Hook->do_action, WP_Hook->apply_filters, HCaptcha\Migrations\Migrations->HCaptcha\Migrations\{closure}, HCaptcha\Migrations\Migrations->create_as_action, as_enqueue_async_action, ActionScheduler_ActionFactory->create, ActionScheduler_ActionFactory->store_unique_action, ActionScheduler_HybridStore->save_action, ActionScheduler_DBStoreMigrator->save_action, ActionScheduler_DBStore->save_action, ActionScheduler_DBStore->save_action_to_db
[24-Mar-2025 13:08:14 UTC] Caught exception while enqueuing action "async_migrate_4_11_0": Error saving action: Error saving action: Table 'uaosufhuas.wp_actionscheduler_actions' doesn't exist
[24-Mar-2025 13:08:14 UTC] WordPress database error Table 'uaosufhuas.wp_actionscheduler_actions' doesn't exist for query SELECT a.action_id FROM wp_actionscheduler_actions a WHERE 1=1 AND a.hook='action_scheduler/migration_hook' AND a.status IN ('in-progress') ORDER BY a.scheduled_date_gmt ASC LIMIT 0, 1 made by require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('wp_loaded'), WP_Hook->do_action, WP_Hook->apply_filters, Action_Scheduler\Migration\Controller->schedule_migration, Action_Scheduler\Migration\Scheduler->is_migration_scheduled, as_next_scheduled_action, ActionScheduler_Store->query_action, ActionScheduler_HybridStore->query_actions, ActionScheduler_DBStore->query_actions
[24-Mar-2025 13:08:14 UTC] WordPress database error Table 'uaosufhuas.wp_actionscheduler_actions' doesn't exist for query SELECT a.action_id FROM wp_actionscheduler_actions a WHERE 1=1 AND a.hook='action_scheduler/migration_hook' AND a.status IN ('pending') ORDER BY a.scheduled_date_gmt ASC LIMIT 0, 1 made by require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('wp_loaded'), WP_Hook->do_action, WP_Hook->apply_filters, Action_Scheduler\Migration\Controller->schedule_migration, Action_Scheduler\Migration\Scheduler->is_migration_scheduled, as_next_scheduled_action, ActionScheduler_Store->query_action, ActionScheduler_HybridStore->query_actions, ActionScheduler_DBStore->query_actions
[24-Mar-2025 13:08:15 UTC] WordPress database error Table 'uaosufhuas.wp_actionscheduler_actions' doesn't exist for query SELECT COUNT(DISTINCT claim_id) FROM wp_actionscheduler_actions WHERE claim_id != 0 AND status IN ( 'pending', 'in-progress') made by shutdown_action_hook, do_action('shutdown'), WP_Hook->do_action, WP_Hook->apply_filters, ActionScheduler_QueueRunner->maybe_dispatch_async_request, ActionScheduler_AsyncRequest_QueueRunner->maybe_dispatch, ActionScheduler_AsyncRequest_QueueRunner->allow, ActionScheduler_Abstract_QueueRunner->has_maximum_concurrent_batches, ActionScheduler_HybridStore->get_claim_count, ActionScheduler_DBStore->get_claim_count
[24-Mar-2025 13:08:15 UTC] WordPress database error Table 'uaosufhuas.wp_actionscheduler_actions' doesn't exist for query SELECT count(a.action_id) FROM wp_actionscheduler_actions a WHERE 1=1 AND a.status IN ('pending') AND a.scheduled_date_gmt <= '2025-03-24 13:08:15' made by shutdown_action_hook, do_action('shutdown'), WP_Hook->do_action, WP_Hook->apply_filters, ActionScheduler_QueueRunner->maybe_dispatch_async_request, ActionScheduler_AsyncRequest_QueueRunner->maybe_dispatch, ActionScheduler_AsyncRequest_QueueRunner->allow, ActionScheduler_Store->has_pending_actions_due, ActionScheduler_HybridStore->query_actions, ActionScheduler_DBStore->query_actions
[24-Mar-2025 13:08:15 UTC] WordPress database error Table 'uaosufhuas.wp_actionscheduler_actions' doesn't exist for query SELECT a.action_id FROM wp_actionscheduler_actions a LEFT JOIN wp_actionscheduler_groups g ON g.group_id=a.group_id WHERE 1=1 AND g.slug='hcaptcha' AND a.hook='async_migrate_4_11_0' AND a.args='[]' AND a.status IN ('pending', 'in-progress', 'failed', 'canceled') ORDER BY a.scheduled_date_gmt ASC LIMIT 0, 5 made by require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('init'), WP_Hook->do_action, WP_Hook->apply_filters, ActionScheduler::{closure}, do_action('action_scheduler_init'), WP_Hook->do_action, WP_Hook->apply_filters, HCaptcha\Migrations\Migrations->HCaptcha\Migrations\{closure}, HCaptcha\Migrations\Migrations->create_as_action, as_get_scheduled_actions, ActionScheduler_HybridStore->query_actions, ActionScheduler_DBStore->query_actions
[24-Mar-2025 13:08:15 UTC] WordPress database error Table 'uaosufhuas.wp_actionscheduler_actions' doesn't exist for query SELECT a.action_id FROM wp_actionscheduler_actions a LEFT JOIN wp_actionscheduler_groups g ON g.group_id=a.group_id WHERE 1=1 AND g.slug='hcaptcha' AND a.hook='async_migrate_4_11_0' AND a.args='[]' AND a.status IN ('pending') ORDER BY a.scheduled_date_gmt ASC LIMIT 0, 1 made by require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('init'), WP_Hook->do_action, WP_Hook->apply_filters, ActionScheduler::{closure}, do_action('action_scheduler_init'), WP_Hook->do_action, WP_Hook->apply_filters, HCaptcha\Migrations\Migrations->HCaptcha\Migrations\{closure}, HCaptcha\Migrations\Migrations->create_as_action, as_enqueue_async_action, ActionScheduler_ActionFactory->create, ActionScheduler_ActionFactory->store_unique_action, ActionScheduler_HybridStore->find_action, ActionScheduler_Store->find_action, ActionScheduler_DBStore->query_actions
[24-Mar-2025 13:08:15 UTC] WordPress database error Table 'uaosufhuas.wp_actionscheduler_groups' doesn't exist for query SELECT group_id FROM wp_actionscheduler_groups WHERE slug='hcaptcha' made by require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('init'), WP_Hook->do_action, WP_Hook->apply_filters, ActionScheduler::{closure}, do_action('action_scheduler_init'), WP_Hook->do_action, WP_Hook->apply_filters, HCaptcha\Migrations\Migrations->HCaptcha\Migrations\{closure}, HCaptcha\Migrations\Migrations->create_as_action, as_enqueue_async_action, ActionScheduler_ActionFactory->create, ActionScheduler_ActionFactory->store_unique_action, ActionScheduler_HybridStore->save_action, ActionScheduler_DBStoreMigrator->save_action, ActionScheduler_DBStore->save_action, ActionScheduler_DBStore->save_action_to_db, ActionScheduler_DBStore->get_group_ids
[24-Mar-2025 13:08:15 UTC] WordPress database error Table 'uaosufhuas.wp_actionscheduler_groups' doesn't exist for query SHOW FULL COLUMNS FROM `wp_actionscheduler_groups` made by require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('init'), WP_Hook->do_action, WP_Hook->apply_filters, ActionScheduler::{closure}, do_action('action_scheduler_init'), WP_Hook->do_action, WP_Hook->apply_filters, HCaptcha\Migrations\Migrations->HCaptcha\Migrations\{closure}, HCaptcha\Migrations\Migrations->create_as_action, as_enqueue_async_action, ActionScheduler_ActionFactory->create, ActionScheduler_ActionFactory->store_unique_action, ActionScheduler_HybridStore->save_action, ActionScheduler_DBStoreMigrator->save_action, ActionScheduler_DBStore->save_action, ActionScheduler_DBStore->save_action_to_db, ActionScheduler_DBStore->get_group_ids, ActionScheduler_DBStore->create_group
[24-Mar-2025 13:08:15 UTC] WordPress database error Table 'uaosufhuas.wp_actionscheduler_actions' doesn't exist for query 
INSERT INTO wp_actionscheduler_actions ( `hook`, `status`, `scheduled_date_gmt`, `scheduled_date_local`, `schedule`, `group_id`, `priority`, `args` )
SELECT 'async_migrate_4_11_0', 'pending', '2025-03-24 13:08:15', '2025-03-24 13:08:15', 'O:28:\"ActionScheduler_NullSchedule\":0:{}', 0, 10, '[]' FROM DUAL
WHERE ( SELECT NULL FROM DUAL ) IS NULL made by require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('init'), WP_Hook->do_action, WP_Hook->apply_filters, ActionScheduler::{closure}, do_action('action_scheduler_init'), WP_Hook->do_action, WP_Hook->apply_filters, HCaptcha\Migrations\Migrations->HCaptcha\Migrations\{closure}, HCaptcha\Migrations\Migrations->create_as_action, as_enqueue_async_action, ActionScheduler_ActionFactory->create, ActionScheduler_ActionFactory->store_unique_action, ActionScheduler_HybridStore->save_action, ActionScheduler_DBStoreMigrator->save_action, ActionScheduler_DBStore->save_action, ActionScheduler_DBStore->save_action_to_db
[24-Mar-2025 13:08:15 UTC] Caught exception while enqueuing action "async_migrate_4_11_0": Error saving action: Error saving action: Table 'uaosufhuas.wp_actionscheduler_actions' doesn't exist
[24-Mar-2025 13:08:15 UTC] WordPress database error Table 'uaosufhuas.wp_actionscheduler_actions' doesn't exist for query SELECT a.action_id FROM wp_actionscheduler_actions a WHERE 1=1 AND a.hook='action_scheduler/migration_hook' AND a.status IN ('in-progress') ORDER BY a.scheduled_date_gmt ASC LIMIT 0, 1 made by require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('wp_loaded'), WP_Hook->do_action, WP_Hook->apply_filters, Action_Scheduler\Migration\Controller->schedule_migration, Action_Scheduler\Migration\Scheduler->is_migration_scheduled, as_next_scheduled_action, ActionScheduler_Store->query_action, ActionScheduler_HybridStore->query_actions, ActionScheduler_DBStore->query_actions
[24-Mar-2025 13:08:15 UTC] WordPress database error Table 'uaosufhuas.wp_actionscheduler_actions' doesn't exist for query SELECT a.action_id FROM wp_actionscheduler_actions a WHERE 1=1 AND a.hook='action_scheduler/migration_hook' AND a.status IN ('pending') ORDER BY a.scheduled_date_gmt ASC LIMIT 0, 1 made by require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('wp_loaded'), WP_Hook->do_action, WP_Hook->apply_filters, Action_Scheduler\Migration\Controller->schedule_migration, Action_Scheduler\Migration\Scheduler->is_migration_scheduled, as_next_scheduled_action, ActionScheduler_Store->query_action, ActionScheduler_HybridStore->query_actions, ActionScheduler_DBStore->query_actions
[24-Mar-2025 13:08:15 UTC] WordPress database error Table 'uaosufhuas.wp_actionscheduler_actions' doesn't exist for query SELECT a.action_id FROM wp_actionscheduler_actions a WHERE 1=1 AND a.status IN ('complete') AND a.last_attempt_gmt <= '2025-02-21 13:08:15' LIMIT 0, 20 made by do_action_ref_array('action_scheduler_run_queue'), WP_Hook->do_action, WP_Hook->apply_filters, ActionScheduler_QueueRunner->run, ActionScheduler_Abstract_QueueRunner->run_cleanup, ActionScheduler_QueueCleaner->clean, ActionScheduler_QueueCleaner->delete_old_actions, ActionScheduler_QueueCleaner->clean_actions, ActionScheduler_HybridStore->query_actions, ActionScheduler_DBStore->query_actions
[24-Mar-2025 13:08:15 UTC] WordPress database error Table 'uaosufhuas.wp_actionscheduler_actions' doesn't exist for query SELECT a.action_id FROM wp_actionscheduler_actions a WHERE 1=1 AND a.status IN ('canceled') AND a.last_attempt_gmt <= '2025-02-21 13:08:15' LIMIT 0, 20 made by do_action_ref_array('action_scheduler_run_queue'), WP_Hook->do_action, WP_Hook->apply_filters, ActionScheduler_QueueRunner->run, ActionScheduler_Abstract_QueueRunner->run_cleanup, ActionScheduler_QueueCleaner->clean, ActionScheduler_QueueCleaner->delete_old_actions, ActionScheduler_QueueCleaner->clean_actions, ActionScheduler_HybridStore->query_actions, ActionScheduler_DBStore->query_actions
[24-Mar-2025 13:08:15 UTC] WordPress database error Table 'uaosufhuas.wp_actionscheduler_actions' doesn't exist for query SELECT a.action_id FROM wp_actionscheduler_actions a WHERE 1=1 AND a.status IN ('pending') AND a.last_attempt_gmt <= '2025-03-24 13:03:15' AND a.claim_id != 0 LIMIT 0, 20 made by do_action_ref_array('action_scheduler_run_queue'), WP_Hook->do_action, WP_Hook->apply_filters, ActionScheduler_QueueRunner->run, ActionScheduler_Abstract_QueueRunner->run_cleanup, ActionScheduler_QueueCleaner->clean, ActionScheduler_QueueCleaner->reset_timeouts, ActionScheduler_HybridStore->query_actions, ActionScheduler_DBStore->query_actions
[24-Mar-2025 13:08:15 UTC] WordPress database error Table 'uaosufhuas.wp_actionscheduler_actions' doesn't exist for query SELECT a.action_id FROM wp_actionscheduler_actions a WHERE 1=1 AND a.status IN ('in-progress') AND a.last_attempt_gmt <= '2025-03-24 13:03:15' LIMIT 0, 20 made by do_action_ref_array('action_scheduler_run_queue'), WP_Hook->do_action, WP_Hook->apply_filters, ActionScheduler_QueueRunner->run, ActionScheduler_Abstract_QueueRunner->run_cleanup, ActionScheduler_QueueCleaner->clean, ActionScheduler_QueueCleaner->mark_failures, ActionScheduler_HybridStore->query_actions, ActionScheduler_DBStore->query_actions
[24-Mar-2025 13:08:15 UTC] WordPress database error Table 'uaosufhuas.wp_actionscheduler_actions' doesn't exist for query SELECT COUNT(DISTINCT claim_id) FROM wp_actionscheduler_actions WHERE claim_id != 0 AND status IN ( 'pending', 'in-progress') made by do_action_ref_array('action_scheduler_run_queue'), WP_Hook->do_action, WP_Hook->apply_filters, ActionScheduler_QueueRunner->run, ActionScheduler_Abstract_QueueRunner->has_maximum_concurrent_batches, ActionScheduler_HybridStore->get_claim_count, ActionScheduler_DBStore->get_claim_count
[24-Mar-2025 13:08:15 UTC] WordPress database error Table 'uaosufhuas.wp_actionscheduler_claims' doesn't exist for query SHOW FULL COLUMNS FROM `wp_actionscheduler_claims` made by do_action_ref_array('action_scheduler_run_queue'), WP_Hook->do_action, WP_Hook->apply_filters, ActionScheduler_QueueRunner->run, ActionScheduler_QueueRunner->do_batch, ActionScheduler_HybridStore->stake_claim, ActionScheduler_DBStore->stake_claim, ActionScheduler_DBStore->generate_claim_id
[24-Mar-2025 13:08:15 UTC] WordPress database error Table 'uaosufhuas.wp_actionscheduler_actions' doesn't exist for query UPDATE wp_actionscheduler_actions SET claim_id=0, last_attempt_gmt='2025-03-24 13:08:15', last_attempt_local='2025-03-24 09:08:15' WHERE claim_id = 0 AND scheduled_date_gmt <= '2025-03-24 13:08:15' AND status='pending' ORDER BY priority ASC, attempts ASC, scheduled_date_gmt ASC, action_id ASC LIMIT 25 made by do_action_ref_array('action_scheduler_run_queue'), WP_Hook->do_action, WP_Hook->apply_filters, ActionScheduler_QueueRunner->run, ActionScheduler_QueueRunner->do_batch, ActionScheduler_HybridStore->stake_claim, ActionScheduler_DBStore->stake_claim, ActionScheduler_DBStore->claim_actions
[24-Mar-2025 13:08:15 UTC] PHP Fatal error:  Uncaught RuntimeException: Unable to claim actions. Database error: Table 'uaosufhuas.wp_actionscheduler_actions' doesn't exist. in /home/bhbhbhb/public_html/wp-content/plugins/hcaptcha-for-forms-and-more/vendor/woocommerce/action-scheduler/classes/data-stores/ActionScheduler_DBStore.php:1016
Stack trace:
#0 /home/bhbhbhb/public_html/wp-content/plugins/hcaptcha-for-forms-and-more/vendor/woocommerce/action-scheduler/classes/data-stores/ActionScheduler_DBStore.php(861): ActionScheduler_DBStore->claim_actions()
#1 /home/bhbhbhb/public_html/wp-content/plugins/hcaptcha-for-forms-and-more/vendor/woocommerce/action-scheduler/classes/data-stores/ActionScheduler_HybridStore.php(253): ActionScheduler_DBStore->stake_claim()
#2 /home/bhbhbhb/public_html/wp-content/plugins/hcaptcha-for-forms-and-more/vendor/woocommerce/action-scheduler/classes/ActionScheduler_QueueRunner.php(179): ActionScheduler_HybridStore->stake_claim()
#3 /home/bhbhbhb/public_html/wp-content/plugins/hcaptcha-for-forms-and-more/vendor/woocommerce/action-scheduler/classes/ActionScheduler_QueueRunner.php(158): ActionScheduler_QueueRunner->do_batch()
#4 /home/bhbhbhb/public_html/wp-includes/class-wp-hook.php(324): ActionScheduler_QueueRunner->run()
#5 /home/bhbhbhb/public_html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#6 /home/bhbhbhb/public_html/wp-includes/plugin.php(565): WP_Hook->do_action()
#7 /home/bhbhbhb/public_html/wp-cron.php(191): do_action_ref_array()
#8 {main}
  thrown in /home/bhbhbhb/public_html/wp-content/plugins/hcaptcha-for-forms-and-more/vendor/woocommerce/action-scheduler/classes/data-stores/ActionScheduler_DBStore.php on line 1016
```

**Comment by kagg-design** [comment]
It was tricky to reproduce the issue. It should be fixed in the 4.12.0-RC4: https://drive.google.com/file/d/1k07IISozVZ5d7NmbijwW46CCz4uJAcxp/view?usp=sharing

Could you please confirm?

**Comment by csalzano** [comment]
The same errors are logged while running this version. Do I need to deactivate and reactivate? I used the .zip uploader in the dashboard.

**Comment by kagg-design** [comment]
Thank you for testing. No, you do not need to deactivate/reactivate the plugin.

If RC4 does not work, I need to know more details. Could you create a test site with a minimal set of plugins where the bug is reproducible and give me admin access to it?

Is it a fresh site where you have a problem? Could you send a link to your production website?

Also, getting the System Info from the hCaptcha plugin would be helpful.

Feel free to share all the details on my email info@kagg.eu if you have any concerns.

**Comment by csalzano** [comment]
I learned that my site still had WooCommerce data despite no longer using the WooCommerce plugin. Lots of options. I added this to my wp-config.php file, installed and removed WooCommerce:

```
// Remove all WooCommerce data on uninstall.
define( 'WC_REMOVE_ALL_DATA', true );
```

However, the same errors are still logged when I activate hCaptcha for WordPress 4.12.0.

`[11-Apr-2025 14:54:10 UTC] PHP Fatal error:  Uncaught RuntimeException: Unable to claim actions. Database error: Table 'uaosufhuas.wp_actionscheduler_actions' doesn't exist.`

**Comment by kagg-design** [comment]
I have recognized the issue. Your database is in the improper state. The tables like 'wp_action_scheduler_xxx' are deleted, but some Action Scheduler options are still there, reporting to the AS that tables exist. This prevents AS from recreation of tables on the fly.

To fix it, just visit the Tootls->Scheduled Actions page in the admin, and AS will forcely re-create its tables.

Or, you can run a command `wp action-scheduler fix-schema` which exists especially for your case.

**Comment by csalzano** [comment]
Thanks. I reactivated hCaptcha for WordPress, ran that wp-cli command, and these lines were written to debug.log. Nothing else since, I think this may have fixed the other errors.

```
[14-Apr-2025 13:00:10 UTC] WordPress database error Can't DROP 'hcaptcha_id'; check that column/key exists for query DROP INDEX hcaptcha_id on wp_hcaptcha_events made by do_action('wp_ajax_as_async_request_queue_runner'), WP_Hook->do_action, WP_Hook->apply_filters, WP_Async_Request->maybe_handle, ActionScheduler_AsyncRequest_QueueRunner->handle, do_action('action_scheduler_run_queue'), WP_Hook->do_action, WP_Hook->apply_filters, ActionScheduler_QueueRunner->run, ActionScheduler_QueueRunner->do_batch, ActionScheduler_Abstract_QueueRunner->process_action, ActionScheduler_Action->execute, do_action_ref_array('async_migrate_4_11_0'), WP_Hook->do_action, WP_Hook->apply_filters, HCaptcha\Migrations\Migrations->async_migrate_4_11_0
[14-Apr-2025 13:00:25 UTC] hCaptcha Plugin:  Migration of hCaptcha Plugin to 4.11.0 completed.
```

**Comment by kagg-design** [comment]
Thank you for confirmation; all good. You can ignore Can't DROP 'hcaptcha_id' error.
